export const issuesConstants = {
  GET_REPO_ISSUES: 'issues/GET_REPO_ISSUES',
  SET_REPO_ISSUES: 'issues/SET_REPO_ISSUES',
  SET_ISSUES_STATE: 'issues/SET_ISSUES_STATE',
  SET_ISSUES_HAS_NEXT_PAGE: 'issues/SET_ISSUES_HAS_NEXT_PAGE',
  SET_ISSUES_HAS_PREV_PAGE: 'issues/SET_ISSUES_HAS_PREV_PAGE',
  CLEAR_ISSUES_HAS_NEXT_AND_PREV_PAGES:
    'issues/CLEAR_ISSUES_HAS_NEXT_AND_PREV_PAGES',
  SET_CURRENT_ISSUES_PAGE: 'issues/SET_CURRENT_ISSUES_PAGE',
  RESET_CURRENT_ISSUES_PAGE: 'issues/RESET_CURRENT_ISSUES_PAGE',
};
